package cn.example.springboot.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2020-03-21T22:05:19.456+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://www.springboot.example.cn/webservice", name = "authorPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthorPortType {

    @WebMethod
    @RequestWrapper(localName = "getAuthorByName", targetNamespace = "http://www.springboot.example.cn/webservice", className = "cn.example.springboot.webservice.GetAuthorByName")
    @ResponseWrapper(localName = "getAuthorByNameResponse", targetNamespace = "http://www.springboot.example.cn/webservice", className = "cn.example.springboot.webservice.GetAuthorByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AuthorDto getAuthorByName(
            @WebParam(name = "authorName", targetNamespace = "")
                    String authorName
    );

    @WebMethod
    @RequestWrapper(localName = "getAuthorList", targetNamespace = "http://www.springboot.example.cn/webservice", className = "cn.example.springboot.webservice.GetAuthorList")
    @ResponseWrapper(localName = "getAuthorListResponse", targetNamespace = "http://www.springboot.example.cn/webservice", className = "cn.example.springboot.webservice.GetAuthorListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<AuthorDto> getAuthorList();

    @WebMethod
    @RequestWrapper(localName = "getAuthorString", targetNamespace = "http://www.springboot.example.cn/webservice", className = "cn.example.springboot.webservice.GetAuthorString")
    @ResponseWrapper(localName = "getAuthorStringResponse", targetNamespace = "http://www.springboot.example.cn/webservice", className = "cn.example.springboot.webservice.GetAuthorStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getAuthorString(
            @WebParam(name = "authorName", targetNamespace = "")
                    String authorName
    );
}
